server:
  address: 127.0.0.1
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/video_reply_telegram_bot?useUnicode=true&rewriteBatchedStatements=true&useSSL=false
    username: video_reply_telegram_bot
    password: video_reply_telegram_bot
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 15
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: false # manual
    change-log: classpath:changelog.xml

#logging:
#  level:
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

liquibase:
  # TODO change the value below to true to enable liquibase
  manual: false

logRestRequestWebInterceptor:
  enabled: true

s3:
  bucket: bucket-name-tbd
  accessKey: EXTERNAL
  secretKey: EXTERNAL
  region: us-west-1
  endpoint: https://s3.us-west-1.wasabisys.com

elk:
  host: elk.cmlteam.com
  port: 10443
  application: video_reply_telegram_bot